import json,uuid,re,random
from datetime import datetime,timedelta,timezone
BASE='/home/alexandre/code/personal/ant_abrige_hackathon/AI_synthetic_data/'
OUT=BASE+'batch_rare_neuroheme.json'
random.seed(881)
# diagnosis,title,sex,age,chief,findings,test,plan,follow,warnings,medication,specialist
C=[
('Myasthenia gravis','Myasthenia gravis review for bulbar fatigability','female',32,'drooping eyelids, double vision, and chewing fatigue that worsens late in the day','fatigable ptosis, nasal speech after counting, positive acetylcholine-receptor antibodies, and decrement on repetitive stimulation supported postsynaptic neuromuscular-junction disease','chest CT for thymoma, pulmonary function baseline, and swallowing assessment','start pyridostigmine, discuss immunotherapy, review thymectomy eligibility, and make a crisis-prevention plan','neuromuscular clinic in two weeks and respiratory testing this week','shortness of breath, weak cough, inability to swallow saliva, rapidly worsening speech, or inability to hold the head up','pyridostigmine with immunotherapy selection pending','neuromuscular neurologist'),
('Lambert-Eaton myasthenic syndrome','Lambert-Eaton evaluation with malignancy screening','male',61,'proximal leg weakness, dry mouth, and difficulty rising that briefly improves after movement','reduced leg reflexes that facilitated after exercise and positive P/Q-type calcium-channel antibodies supported a presynaptic junction disorder','electrodiagnostic high-frequency stimulation and age-appropriate small-cell lung cancer surveillance','begin amifampridine, consider immunotherapy if needed, and coordinate repeated malignancy screening when initial imaging is negative','neuromuscular clinic in three weeks and oncology surveillance per protocol','new breathing or swallowing difficulty, rapidly worsening weakness, fainting, or severe constipation with abdominal pain','amifampridine with interaction and QT review','neuromuscular neurologist'),
('Chronic inflammatory demyelinating polyneuropathy','CIDP treatment-response and gait assessment','female',49,'eight weeks of progressive symmetric leg and hand weakness with numb feet and falls','proximal and distal weakness, globally reduced reflexes, demyelinating nerve-conduction features, and elevated CSF protein without pleocytosis supported CIDP','baseline disability score, paraprotein evaluation, diabetes and mimic screen, and treatment-response measurements','initiate IVIG and physical therapy, with glucocorticoid or plasma-exchange alternatives discussed if response is inadequate','neuromuscular clinic in four weeks with infusion safety call after the first cycle','new breathing or swallowing trouble, inability to stand, rapidly ascending weakness, chest pain, or symptoms of thrombosis','intravenous immunoglobulin induction','peripheral-nerve neurologist'),
('Guillain-Barre syndrome recovery phase','Guillain-Barre recovery and autonomic follow-up','male',42,'residual foot weakness, neuropathic pain, and fatigue six weeks after hospital treatment','strength and reflexes were slowly improving after a monophasic ascending neuropathy treated with IVIG; there was no new cranial or respiratory decline','serial strength, gait, respiratory symptoms, autonomic review, and rehabilitation assessment','continue graded rehabilitation, fall prevention, pain management, and monitoring for treatment-related fluctuation or evolution toward CIDP','rehabilitation neurology in three weeks and physical therapy twice weekly','new ascending weakness, breathlessness, choking, fainting, sustained racing heartbeat, or loss of walking ability','gabapentin titrated for neuropathic pain','neurorehabilitation physician'),
('Neuromyelitis optica spectrum disorder','AQP4-positive NMOSD relapse-prevention planning','female',37,'painful vision loss followed months later by severe leg weakness and bladder retention','AQP4-IgG was positive and MRI showed optic-nerve enhancement plus longitudinally extensive transverse myelitis, supporting NMOSD','baseline infection screening, immunoglobulins, pregnancy planning, and disability assessment before preventive therapy','treat any active relapse urgently with high-dose intravenous glucocorticoids and plasma exchange if needed, then start targeted relapse prevention','neuroimmunology in one week and ophthalmology within two weeks','new vision loss, rapidly worsening weakness, urinary retention, severe vomiting or hiccups, or breathing difficulty','eculizumab, inebilizumab, satralizumab, or rituximab shared selection','neuroimmunologist'),
('Myelin oligodendrocyte glycoprotein antibody-associated disease','MOGAD consultation after optic neuritis recurrence','male',28,'a second episode of painful bilateral visual blurring after a prior steroid-responsive attack','live cell-based serum MOG-IgG was positive during an optic-neuritis phenotype and MRI findings were reviewed for alternatives','repeat antibody context review, visual testing, MRI brain-orbits-spine, and infection screening before long-term therapy','treat the acute attack promptly with glucocorticoids and taper carefully; discuss maintenance IVIG or other therapy because attacks have recurred','neuroimmunology in ten days and neuro-ophthalmology this week','new or worsening vision loss, weakness, numbness rising up the body, urinary retention, confusion, or seizure','intravenous glucocorticoids followed by individualized maintenance discussion','neuroimmunologist'),
('Huntington disease','Huntington disease motor and family-planning visit','female',44,'involuntary movements, irritability, and worsening organization with a parent affected by Huntington disease','neurologic examination showed chorea and impaired saccades, and prior predictive testing documented a pathogenic HTT CAG expansion','baseline functional, psychiatric, swallowing, driving, and genetic-counseling assessments','use multidisciplinary symptom treatment, address mood and safety first, discuss chorea medication, and support advance and family planning without coercion','Huntington specialty clinic in six weeks and behavioral health in two weeks','suicidal thoughts, unsafe behavior, choking, repeated falls, sudden neurologic change, or inability of caregivers to maintain safety','tetrabenazine-class therapy considered after mood assessment','movement-disorders neurologist'),
('Spinocerebellar ataxia type 3','SCA3 evaluation for progressive gait and eye-movement disorder','male',39,'slowly progressive imbalance, leg stiffness, and double vision with several affected relatives','gait ataxia, hyperreflexia, impaired eye movements, and a pathogenic ATXN3 CAG expansion supported spinocerebellar ataxia type 3','swallowing, sleep, vision, falls, neuropathy, and rehabilitation baselines plus family genetic counseling','provide coordinated physical, occupational, speech, and symptom-directed therapy; avoid unsupported disease-modifying claims and offer research information','ataxia clinic in three months and balance therapy next week','sudden change from baseline, repeated choking, serious fall, new breathing difficulty, or suicidal thoughts','baclofen cautiously for function-limiting spasticity','ataxia neurologist'),
('Amyotrophic lateral sclerosis','ALS multidisciplinary respiratory and communication planning','male',58,'progressive hand weakness, muscle twitching, and slurred speech without sensory loss','upper and lower motor-neuron signs across multiple regions with supportive EMG findings and exclusion of structural mimics supported ALS','sitting and supine vital capacity, cough strength, swallowing, nutrition, communication, and genetic counseling assessments','offer riluzole and discuss edaravone eligibility, noninvasive ventilation, cough assistance, nutrition options, communication access, and goals of care','multidisciplinary ALS clinic in four weeks and respiratory therapy this week','breathlessness at rest, morning confusion, inability to clear secretions, choking, or rapidly declining intake','riluzole with liver monitoring','ALS neurologist'),
('Progressive supranuclear palsy','PSP falls and swallowing safety assessment','female',71,'early backward falls, slowed movement, and difficulty looking down','vertical supranuclear gaze palsy, axial rigidity, slowed saccades, and early postural instability supported progressive supranuclear palsy','swallow evaluation, cognition and mood screen, mobility and home-safety assessment, and medication review','use cue-based therapy, weighted mobility support when appropriate, speech-swallow care, and a cautious levodopa trial while setting realistic expectations','movement clinic in six weeks and home safety visit this month','head injury after a fall, choking, new inability to walk, sudden one-sided weakness, or acute confusion','carbidopa-levodopa time-limited trial','movement-disorders neurologist'),
('Multiple system atrophy','MSA autonomic and mobility management visit','male',63,'parkinsonism with urinary retention, erectile dysfunction, and marked lightheadedness on standing','orthostatic blood-pressure drop, poor levodopa response, urinary dysfunction, and cerebellar signs supported probable multiple system atrophy','supine and standing pressures, postvoid residual, sleep-stridor review, swallowing study, and rehabilitation assessment','use nonpharmacologic pressure support, carefully titrate pressor therapy, coordinate bladder care, and evaluate nocturnal stridor urgently','autonomic neurology in three weeks and urology within one month','fainting with injury, inability to urinate, noisy breathing during sleep, choking, chest pain, or acute neurologic change','midodrine with supine-hypertension precautions','autonomic neurologist'),
('Corticobasal syndrome','Corticobasal syndrome diagnostic and function review','female',67,'progressive one-sided arm stiffness, apraxia, and a limb that sometimes feels alien','marked asymmetric rigidity, cortical sensory loss, limb apraxia, and myoclonus supported corticobasal syndrome while underlying pathology remained uncertain','brain MRI review, cognitive-language assessment, occupational therapy evaluation, and exclusion of treatable mimics','focus on occupational and physical therapy, communication support, a cautious levodopa trial, and caregiver safety planning','cognitive-movement clinic in six weeks and occupational therapy next week','sudden weakness unlike the gradual pattern, choking, serious fall, acute confusion, or unsafe behavior','carbidopa-levodopa trial with stop criteria','behavioral neurologist'),
('Narcolepsy type 1','Narcolepsy type 1 treatment and driving-safety visit','female',22,'daily irresistible sleep episodes and brief knee buckling triggered by laughter','clear cataplexy accompanied chronic sleepiness; overnight polysomnography excluded insufficient sleep and the multiple sleep latency test showed short latency with sleep-onset REM periods','sleep schedule and medication review, driving-risk assessment, and orexin testing only if diagnostic uncertainty remains','establish adequate scheduled sleep, strategic naps, wake-promoting therapy, and cataplexy treatment while restricting driving until controlled','sleep medicine in four weeks with weekly sleep and episode diary','sleepiness while driving, prolonged unresponsiveness, injury during cataplexy, severe medication reaction, or suicidal thoughts','modafinil for sleepiness with cataplexy therapy selection','sleep neurologist'),
('Dravet syndrome','Dravet syndrome seizure-rescue and medication review','female',9,'prolonged fever-triggered convulsive seizures despite several antiseizure medicines','onset in infancy, multiple seizure types, developmental slowing, and a pathogenic SCN1A variant supported Dravet syndrome','seizure and developmental baseline, ECG if fenfluramine is considered, rescue-plan review, and school safety coordination','optimize syndrome-appropriate therapy, avoid sodium-channel blockers that can worsen seizures, provide rescue medication, and address temperature and water safety','pediatric epilepsy in one month and school nurse training this week','a convulsion lasting five minutes or the individualized threshold, repeated seizures without recovery, breathing difficulty, injury, or unusual prolonged sleepiness','valproate with clobazam and syndrome-specific add-on review','pediatric epileptologist'),
('Lennox-Gastaut syndrome','Lennox-Gastaut drop-seizure management conference','male',14,'frequent tonic and drop seizures with injuries and developmental impairment','multiple drug-resistant seizure types, slow spike-wave on EEG, and paroxysmal fast activity during sleep supported Lennox-Gastaut syndrome','seizure counts, medication levels when indicated, sleep EEG review, bone health, swallowing, and helmet assessment','optimize broad-spectrum treatment, prescribe rescue therapy, discuss ketogenic diet and device or surgical options, and strengthen injury prevention','complex epilepsy clinic in four weeks and dietitian in two weeks','a prolonged seizure, repeated seizures without recovery, breathing difficulty, major head injury, or sudden change in alertness','rufinamide or clobazam within a rational polytherapy review','pediatric epileptologist'),
('Rett syndrome','Rett syndrome breathing, hand function, and scoliosis review','female',12,'loss of purposeful hand use, stereotypic hand movements, irregular breathing while awake, and progressive scoliosis','developmental regression after an initially typical period, characteristic hand stereotypies, and a pathogenic MECP2 variant supported Rett syndrome','ECG QT assessment, swallowing and nutrition review, sleep, breathing, mobility, bone health, and scoliosis monitoring','continue coordinated therapies and communication access, treat seizures and tone individually, discuss trofinetide, and monitor cardiac and respiratory risk','Rett multidisciplinary clinic in two months and orthopedics this month','prolonged seizure, blue color, sustained breathing difficulty, fainting, aspiration symptoms, or severe pain','trofinetide eligibility and tolerability discussion','developmental neurologist'),
('Duchenne muscular dystrophy','Duchenne muscular dystrophy cardiopulmonary surveillance visit','male',11,'increasing difficulty rising from the floor and climbing stairs with known dystrophinopathy','proximal weakness, calf enlargement, elevated creatine kinase, and a pathogenic DMD variant established Duchenne muscular dystrophy','pulmonary function, cough strength, ECG and cardiac imaging, bone health, vitamin D, and contracture assessment','continue glucocorticoid therapy, stretching and mobility support, initiate cardiac protection as indicated, and review mutation-specific eligibility','neuromuscular clinic in three months with cardiology and pulmonary visits this month','breathlessness, weak cough with infection, chest pain, fainting, dark urine after muscle injury, or fracture','deflazacort with cardiac therapy per surveillance','pediatric neuromuscular specialist'),
('Spinal muscular atrophy type 2','SMA type 2 disease-modifying therapy follow-up','female',18,'increased transfer difficulty and fatigue with an established childhood-onset motor-neuron disorder','genetic testing documented biallelic SMN1 loss; current examination showed proximal weakness without loss of all sitting ability','standardized motor scale, respiratory and cough testing, swallowing, nutrition, spine, hip, and treatment laboratory assessment','continue disease-modifying therapy through shared review, optimize respiratory support, equipment, bone health, and contracture prevention','SMA multidisciplinary clinic in three months and respiratory therapy this month','breathing difficulty, ineffective cough, choking, rapid loss of function, severe constipation with pain, or equipment failure affecting safety','nusinersen, risdiplam, or prior gene-therapy follow-up according to treatment history','SMA neuromuscular specialist'),
('Facioscapulohumeral muscular dystrophy','FSHD scapular weakness and pain management visit','male',35,'difficulty lifting the arms, asymmetric shoulder-blade winging, and inability to fully close the eyes during sleep','facial and scapular weakness with asymmetric humeral involvement and molecular confirmation supported FSHD','baseline strength and function, retinal and hearing review when indicated, respiratory testing for risk factors, and pain assessment','use targeted low-intensity conditioning, scapular mechanics support, eye protection, pain treatment, and surgical consultation only for selected fixation candidates','muscular dystrophy clinic in four months and physical therapy next week','new breathing difficulty, aspiration, sudden weakness unlike baseline, severe eye pain or injury, or a fall with major injury','lubricating eye ointment and individualized analgesia','muscular dystrophy neurologist'),
('Severe hemophilia A','Severe hemophilia A prophylaxis and inhibitor surveillance','male',24,'recurrent joint bleeds despite missed prophylaxis doses and new ankle swelling','factor VIII activity was below one percent and the current episode was consistent with hemarthrosis; inhibitor status required confirmation','factor VIII inhibitor assay, joint ultrasound as needed, CBC, treatment-level review, and physical therapy assessment','treat the suspected bleed immediately, restore individualized prophylaxis, avoid intramuscular injections and NSAIDs, and address adherence barriers without blame','hemophilia treatment center within seventy-two hours','head injury, severe headache, neck swelling, abdominal or flank pain, uncontrolled bleeding, or a painful rapidly enlarging joint','factor VIII replacement or emicizumab prophylaxis according to inhibitor status','hemophilia hematologist'),
('von Willebrand disease type 3','Type 3 von Willebrand disease perioperative planning','female',30,'frequent nosebleeds, heavy menstrual bleeding, and an upcoming dental extraction','virtually absent von Willebrand factor with very low factor VIII activity was consistent with type 3 von Willebrand disease','current VWF and factor VIII levels, inhibitor history, CBC and ferritin, procedure details, and prior treatment response','use VWF-containing concentrate for procedural coverage, add antifibrinolytic therapy when appropriate, and coordinate exact dosing with the treatment center','bleeding-disorders clinic one week before the procedure','bleeding that does not stop, vomiting or coughing blood, black stool, severe headache, faintness, or rapidly increasing swelling','plasma-derived VWF-factor VIII concentrate with tranexamic acid consideration','bleeding-disorders hematologist'),
('Paroxysmal nocturnal hemoglobinuria','PNH complement-inhibitor counseling after hemolysis','male',38,'dark morning urine, abdominal pain, fatigue, and a new hepatic-vein thrombosis','flow cytometry showed a large GPI-deficient granulocyte clone with Coombs-negative intravascular hemolysis, supporting PNH','CBC, reticulocytes, LDH, kidney function, thrombosis mapping, marrow-failure assessment, and meningococcal vaccination review','start terminal complement inhibition promptly with required infection prevention, treat thrombosis, and monitor for residual anemia and marrow failure','PNH hematology within three days and anticoagulation follow-up this week','chest pain, breathlessness, severe abdominal pain, neurologic deficit, high fever, stiff neck, or rapidly worsening dark urine','eculizumab or ravulizumab after urgent vaccination and prophylaxis review','PNH hematologist'),
('Aplastic anemia','Severe aplastic anemia transplant and immunotherapy consultation','female',41,'bruising, infections, and fatigue with pancytopenia','hypocellular marrow without malignant infiltration plus severe neutropenia and thrombocytopenia supported acquired aplastic anemia after inherited and secondary causes were assessed','HLA typing, PNH clone testing, viral studies, cytogenetics, donor search, and inherited marrow-failure evaluation when indicated','use urgent transplant evaluation for an appropriate matched donor or antithymocyte globulin plus cyclosporine and eltrombopag when transplant is not selected','marrow-failure clinic in forty-eight hours with twice-weekly blood counts','fever of 100.4 F or higher, uncontrolled bleeding, severe headache, breathlessness, chest pain, or new infection symptoms','horse antithymocyte globulin, cyclosporine, and eltrombopag planning','marrow-failure hematologist'),
('Hereditary spherocytosis','Hereditary spherocytosis hemolysis and gallstone review','male',20,'episodic jaundice, fatigue after viral illnesses, and left-upper-quadrant fullness','spherocytes, reticulocytosis, indirect hyperbilirubinemia, negative antiglobulin testing, and increased osmotic fragility supported hereditary spherocytosis','CBC and reticulocyte trend, bilirubin, iron status, spleen size, gallbladder ultrasound, and family counseling','continue folate when indicated, monitor anemia and gallstones, and discuss splenectomy only for severity with vaccination and infection planning','red-cell disorders clinic in three months','rapid pallor with weakness, fainting, severe abdominal pain, fever after splenectomy, chest pain, or dark urine with reduced output','folic acid based on hemolysis burden and diet','red-cell hematologist'),
('Transfusion-dependent beta thalassemia','Transfusion-dependent beta thalassemia iron-burden review','female',27,'fatigue before scheduled transfusions and difficulty tolerating iron chelation','genotype and lifelong severe anemia established beta thalassemia; MRI showed increased hepatic iron despite regular red-cell transfusions','pretransfusion CBC, ferritin trend, liver and cardiac MRI iron, endocrine, bone, infection, and alloantibody surveillance','maintain phenotype-matched transfusions, adjust chelation to measured iron burden and tolerability, and review curative transplant or gene-therapy eligibility','thalassemia center in four weeks and chelation pharmacy call next week','fever after transfusion, breathing difficulty, chest or back pain, dark urine, fainting, or severe abdominal pain','deferasirox adjusted to organ iron and toxicity monitoring','thalassemia hematologist'),
('Immune thrombotic thrombocytopenic purpura in remission','Immune TTP remission surveillance visit','female',36,'anxiety about relapse after bruising and headache during remission','blood counts and hemolysis markers were currently normal, while prior severe ADAMTS13 deficiency with inhibitor established immune TTP','CBC, smear, LDH, bilirubin, haptoglobin, creatinine, and serial ADAMTS13 activity during remission','continue close surveillance, consider preemptive rituximab for persistently severe ADAMTS13 deficiency, and provide a low-threshold emergency testing plan','TTP clinic in one month or the same day if symptoms recur','new neurologic symptoms, severe headache, unusual bruising, pinpoint rash, chest pain, breathlessness, dark urine, or marked fatigue','preemptive rituximab only if remission ADAMTS13 results support it','TTP hematologist'),
('Waldenstrom macroglobulinemia','Waldenstrom macroglobulinemia viscosity-risk assessment','male',69,'fatigue, headaches, blurred vision, and nosebleeds with an IgM monoclonal protein','marrow lymphoplasmacytic lymphoma plus elevated IgM supported Waldenstrom macroglobulinemia, and symptoms raised concern for hyperviscosity','serum viscosity, fundoscopy, CBC, metabolic panel, neuropathy assessment, MYD88 testing, and treatment-indication review','perform urgent plasma exchange if symptomatic hyperviscosity is confirmed, then choose clone-directed therapy without using IgM level alone as the indication','lymphoma clinic within forty-eight hours','worsening vision, confusion, focal weakness, chest pain, breathlessness, uncontrolled bleeding, or severe headache','bendamustine-rituximab or a BTK inhibitor after genotype and risk review','lymphoplasmacytic lymphoma hematologist'),
('Hairy cell leukemia','Hairy cell leukemia cytopenia and infection planning','male',56,'recurrent infections, fatigue, and abdominal fullness from an enlarged spleen','pancytopenia, splenomegaly, characteristic lymphoid cells, marrow findings, and BRAF V600E supported classic hairy cell leukemia','infection screen, CBC, marrow burden, immunophenotype, BRAF result confirmation, and treatment-indication assessment','treat active infection first, then use purine-analog therapy with appropriate prophylaxis; monitor prolonged immune suppression and blood-count recovery','leukemia clinic in one week with fever plan active immediately','fever of 100.4 F or higher, shaking chills, breathing difficulty, uncontrolled bleeding, severe abdominal pain, or confusion','cladribine with rituximab consideration and infection prophylaxis','hairy-cell leukemia hematologist'),
('Primary myelofibrosis','Primary myelofibrosis symptom and transplant-risk review','female',64,'night sweats, weight loss, early satiety, and worsening anemia','leukoerythroblastosis, splenomegaly, marrow fibrosis, and a JAK2 mutation supported primary myelofibrosis after BCR-ABL1 exclusion','molecular risk panel, cytogenetics, symptom score, transfusion burden, spleen assessment, and transplant evaluation','use risk-adapted therapy, consider a JAK inhibitor for symptoms and spleen burden, address anemia, and refer transplant-eligible higher-risk disease','myeloid neoplasm clinic in two weeks and transplant consultation this month','fever, uncontrolled bleeding, chest pain, severe breathlessness, rapidly enlarging painful abdomen, or new neurologic symptoms','ruxolitinib with blood-count and infection monitoring','myeloproliferative neoplasm hematologist'),
('Uveal melanoma','Uveal melanoma staging after choroidal mass diagnosis','female',53,'flashes, a growing visual-field shadow, and a newly diagnosed pigmented choroidal mass','ocular oncology imaging showed a dome-shaped choroidal lesion with subretinal fluid, supporting uveal melanoma','liver-focused staging imaging, chest imaging, liver tests, tumor prognostic testing discussion, and visual-function baseline','choose plaque brachytherapy or proton therapy based on tumor anatomy, preserve the eye when appropriate, and establish long-term metastatic surveillance','ocular oncology in one week and medical oncology after staging','sudden vision loss, severe eye pain, new neurologic deficit, jaundice, severe abdominal pain, or breathlessness','no systemic drug before staging; local radiation planning','ocular oncologist'),
('Chordoma','Sacral chordoma multidisciplinary treatment planning','male',47,'months of sacral pain, numbness, and bowel urgency with a midline bone mass','MRI and core biopsy showed a brachyury-positive notochordal tumor consistent with chordoma','complete neuraxis-local staging as appropriate, chest imaging, surgical anatomy review, pathology confirmation, and functional baseline','plan en bloc resection when feasible with chordoma-experienced surgery and high-dose conformal radiation; avoid unplanned intralesional procedures','sarcoma board in ten days and spine surgery this week','new urinary retention, loss of bowel control, saddle numbness, rapidly worsening weakness, fever, or uncontrolled pain','multimodal analgesia while definitive local therapy is arranged','chordoma sarcoma oncologist'),
('Gastrointestinal stromal tumor','GIST mutation-directed adjuvant therapy review','female',59,'early satiety and anemia after resection of a gastric stromal tumor','pathology showed a KIT-positive spindle-cell tumor; size, mitotic rate, location, rupture status, and margins defined recurrence risk','KIT and PDGFRA mutation testing, baseline CT abdomen-pelvis, CBC, liver tests, and formal recurrence-risk calculation','use surveillance for sufficiently low risk or mutation-directed adjuvant imatinib for sensitive higher-risk disease; avoid imatinib for resistant PDGFRA D842V','sarcoma oncology in two weeks after molecular results','vomiting blood, black stool, severe abdominal pain, fainting, persistent vomiting, or fever on therapy','imatinib only if genotype and recurrence risk support benefit','GIST medical oncologist'),
('Merkel cell carcinoma','Merkel cell carcinoma nodal staging and treatment plan','male',73,'a rapidly enlarging painless violet skin nodule on a sun-exposed forearm','biopsy showed neuroendocrine carcinoma with cytokeratin-20 dot-like staining, supporting Merkel cell carcinoma','whole-skin and nodal examination, sentinel lymph-node biopsy when clinically node-negative, and stage-appropriate imaging','coordinate wide local excision and radiation based on site and nodal risk; use immune checkpoint therapy for unresectable or metastatic disease','multidisciplinary skin cancer clinic within one week','rapidly enlarging nodes, breathing difficulty, new neurologic symptoms, uncontrolled bleeding, severe pain, or fever during systemic therapy','pembrolizumab or avelumab only for appropriate advanced-stage treatment','Merkel cell carcinoma oncologist')]
FIRST=['Ava','Ben','Camila','Dev','Esme','Finn','Gia','Hale','Ines','Jude','Keira','Luis','Mina','Nico','Opal','Pavel','Quinn','Rey','Sara','Tariq','Uma','Vik','Willa','Xavi','Yara','Zane','Amara','Bram','Cleo','Dane','Elle','Farah','Gabe']
LAST=['Arden','Basu','Cruz','Doyle','Emery','Farrell','Gupta','Holt','Ito','James','Klein','Lopez','Moss','Nolan','Ortega','Perry','Quade','Ramos','Salem','Turner','Usman','Vale','Wong','Xu','Yates','Zhou','Ahmed','Blake','Choi','Dunn','Evans','Flores','Green']
def uid():return str(uuid.uuid4())
def wc(s):return len(re.findall(r"\b[\w'-]+\b",s))
def make_trans(i,c,p):
 d,t,sex,age,chief,findings,test,plan,follow,warn,med,sp=c
 support=['Partner','Parent','Sibling','Adult child'][i%4]
 opens=[
 [(p,f'My main concern is {chief}. I brought a timeline.'),(sp,'We will connect that timeline to the examination, tests, and decisions.'),(p,'Please be direct about uncertainty and emergencies.')],
 [('Clinic nurse','I have reconciled medicines, allergies, and recent urgent visits.'),(p,f'The issue changing daily life is {chief}.'),(sp,'I will review the evidence and then we will build a written plan.')],
 [(support,f'I joined to help record the plan; we have observed {chief}.'),(p,'Please address decisions to me, and my support person can add observations.'),(sp,'Agreed. Your preferences will guide shared decisions.')],
 [(sp,'What would make this visit useful?'),(p,f'I need an explanation and safe plan for {chief}.'),(sp,'I will separate confirmed findings from pending questions.')],
 [(p,f'My symptom log documents {chief}.'),(sp,'Tell me what changed first and what has changed most recently.'),(p,'Function has declined more than the symptom number alone suggests.')],
 [('Fellow',f'The referral question concerns {chief}.'),(sp,'Thank you. I will verify the history directly with the patient.'),(p,'I want to understand the evidence, not just hear a label.')],
 [('Genetic counselor','We can revisit inheritance after the clinical plan is clear.'),(p,f'Today my immediate concern is {chief}.'),(sp,'We will address current safety first and family implications without pressure.')],
 [('Pharmacist','I am here to check interactions, administration, and access.'),(p,f'I need help because of {chief}.'),(sp,'We will align medication details with the diagnosis and monitoring plan.')],
 [('Physical therapist','I assessed transfers, gait, and the activities the patient identified.'),(p,f'The limiting problem is {chief}.'),(sp,'Functional measurements will help us track meaningful change.')],
 [('Telehealth coordinator','Audio, video, identity, location, and emergency contact are confirmed.'),(p,f'I am connecting today for {chief}.'),(sp,'We can make decisions today and arrange any necessary in-person examination.')],
 [(p,f'I am worried that {chief} means the condition is accelerating.'),(sp,'We will compare the pace with objective measures and identify urgent changes.'),(p,'I also want practical steps for tonight.')],
 [('Resident','May I summarize the history for confirmation?'),(p,f'Yes. The central issue is {chief}.'),(sp,'After the summary, the patient will correct anything and choose among options.')],
 ][i%12]
 core=[(sp,f'The key evidence is: {findings}. This pattern supports {d}; no single result was treated as conclusive by itself.'),(p,'What remains uncertain or could still change treatment?'),(sp,f'We reviewed relevant mimics and complications. Next, complete {test}. These steps refine severity, prognosis, or treatment selection.'),(p,'How does the recommended plan fit my current risk and goals?'),(sp,f'We recommend that we {plan}. The medication strategy is {med}. Benefits, important adverse effects, monitoring, and reasonable alternatives were discussed.'),(p,'What should happen after I leave today?'),(sp,f'Keep the condition-specific log and current medication list, and report access barriers. Follow-up is {follow}. The specialty team will review results rather than assuming silence means normal.'),(p,'Please state the emergency signs in plain language.'),(sp,f'Seek immediate assessment for {warn}. Use emergency services for severe or rapidly progressing symptoms; do not drive if weakness, faintness, confusion, sleepiness, or vision makes that unsafe.')]
 closes=[[(p,'My teach-back is: complete the staging, follow the written treatment exactly, and use the emergency plan for rapid change.'),(sp,'Correct. Contact us before changing prescribed therapy.')],[(support,'I recorded the follow-up and warning signs.'),(p,'I understand that routine monitoring must not delay urgent care.'),(sp,'That is accurate; the after-visit summary matches this discussion.')],[('Clinic nurse','Orders, contact numbers, and medication instructions are printed.'),(p,'I know who owns each next step and when to call.'),(sp,'Please notify us if logistics prevent completion.')],[(p,'I choose the recommended approach after discussing benefits and alternatives.'),(sp,'We documented that choice and the monitoring plan.'),(p,'I will bring outside results and an updated medicine list.')]][i%4]
 s='\n\n'.join(f'{a}: {b}' for a,b in opens+core+closes)
 if wc(s)<320:s+=f'\n\n{p}: How should I track change without becoming alarmed by every fluctuation?\n\n{sp}: For {d}, record the specific symptoms, function, treatment timing, and measurements we named. Trends help at {follow}, but home tracking never replaces urgent assessment for {warn}.'
 return s
def make_note(c,p):
 d,t,sex,age,chief,findings,test,plan,follow,warn,med,sp=c; S='He' if sex=='male' else 'She'
 return f'''RARE NEUROLOGY, HEMATOLOGY, OR ONCOLOGY NOTE

Reason: {p} is a {age}-year-old {sex} evaluated for {chief}. The symptom timeline, function, medicines, allergies, recent infections, family history, and prior treatment response were reconciled. {S} participated directly in shared decision-making and identified safety and follow-up priorities.

Diagnostic synthesis: {findings}. Relevant mimics, treatment effects, and organ-threatening complications were considered. The working diagnosis is {d}. The planned studies will refine disease extent, current risk, and therapy selection rather than substitute for clinical assessment.

Assessment: {d}, with manifestations described above. The team reviewed expected course, important uncertainty, family or reproductive implications when relevant, and the distinction between routine contact and emergency evaluation.

Plan: {plan.capitalize()}. Medication strategy: {med}. Complete {test}. Monitoring, material adverse effects, infection or bleeding precautions, interactions, and activity guidance were reviewed. The patient should not independently change treatment. Follow-up is {follow}; the responsible specialty will review results and communicate changes.

Safety: Seek immediate assessment for {warn}. Severe or rapidly progressing symptoms warrant emergency services. The patient completed teach-back, confirmed access to written instructions, and will bring a current medicine list and outside reports. Access, transportation, cost, caregiver, or supply barriers should be reported promptly so logistics can be adjusted without silently interrupting care.'''
def avs(c):
 d,t,sex,age,chief,findings,test,plan,follow,warn,med,sp=c
 return f'We evaluated {chief}. The findings support {d}. Complete {test}. The plan is to {plan}. Medication strategy: {med}. Follow-up is {follow}. Seek immediate care for {warn}. Do not change prescribed treatment without the specialty team.'
R=[]; base=datetime(2024,2,5,8,30,tzinfo=timezone(timedelta(hours=-8)))
for i,c in enumerate(C):
 d,t,sex,age,*_=c; pid,eid=uid(),uid(); p=FIRST[i]+' '+LAST[i]; dt=base+timedelta(days=19*i,hours=i%7,minutes=(13*i)%60); start=dt.isoformat(); end=(dt+timedelta(minutes=50+i%40)).isoformat(); day=dt.date().isoformat(); pref='urn:uuid:'+pid; eref='urn:uuid:'+eid
 def link(x):x['subject']={'reference':pref};x['encounter']={'reference':eref};return x
 rr={'Condition':[link({'resourceType':'Condition','id':uid(),'clinicalStatus':{'coding':[{'code':'active'}]},'verificationStatus':{'coding':[{'code':'confirmed'}]},'code':{'text':d},'recordedDate':day})],
 'Observation':[link({'resourceType':'Observation','id':uid(),'status':'final','code':{'text':d+' key findings'},'effectiveDateTime':start,'valueString':c[5]}),link({'resourceType':'Observation','id':uid(),'status':'final','code':{'text':d+' specialty synthesis'},'effectiveDateTime':start,'valueString':'The integrated clinical pattern supports '+d+'; planned testing refines severity and treatment.'})],
 'MedicationRequest':[link({'resourceType':'MedicationRequest','id':uid(),'status':'active','intent':'plan','medicationCodeableConcept':{'text':c[10]},'authoredOn':day,'dosageInstruction':[{'text':'Use only according to the individualized specialty prescription and monitoring plan.'}]})],
 'ServiceRequest':[link({'resourceType':'ServiceRequest','id':uid(),'status':'active','intent':'order','code':{'text':c[6]},'authoredOn':day})],
 'CarePlan':[link({'resourceType':'CarePlan','id':uid(),'status':'active','intent':'plan','title':d+' individualized care plan','period':{'start':day},'activity':[{'detail':{'description':c[7]}}]})]}
 counts={k:len(v) for k,v in rr.items()}; trans=make_trans(i,c,p); note=make_note(c,p)
 R.append({'id':pid+'::'+eid,'metadata':{'source':'ai-synthetic-fhir-r4','synthetic':True,'patient_id':pid,'encounter_id':eid,'encounter_reference':eref,'date':start,'status':'finished','visit_type':'Rare disease specialty encounter','document_status':'current','related_resource_counts':counts,'visit_title':t},'patient_context':{'patient':{'resourceType':'Patient','id':pid,'name':[{'use':'official','family':LAST[i],'given':[FIRST[i]]}],'gender':sex,'birthDate':f'{dt.year-age}-{i%12+1:02d}-{i*5%27+1:02d}','address':[{'city':['Oakland','San Jose','Sacramento','Fresno','Berkeley'][i%5],'state':'CA','country':'US'}]},'longitudinal_summary':{'resource_counts':{'Patient':1,'Encounter':1,**counts},'condition_labels':[d],'medication_labels':[c[10]]}},'encounter_fhir':{'encounter':{'resourceType':'Encounter','id':eid,'status':'finished','class':{'system':'http://terminology.hl7.org/CodeSystem/v3-ActCode','code':'AMB','display':'ambulatory'},'type':[{'text':t}],'subject':{'reference':pref,'display':p},'participant':[{'individual':{'reference':f'Practitioner/synthetic-neuroheme-{i+1:02d}','display':c[11]}}],'period':{'start':start,'end':end},'reasonCode':[{'text':c[4]}],'location':[{'location':{'reference':'Location/synthetic-rare-specialty-center','display':'Synthetic Rare Specialty Center'}}]},'related_resources':rr},'transcript':trans,'note':note,'after_visit_summary':avs(c),'after_visit_summary_provenance':{'method':'deterministic_extractive_v1','source':'clinical_note_assessment_and_plan','review_status':'not_clinically_reviewed'}})
json.dump(R,open(OUT,'w'),indent=2,ensure_ascii=False)
print(len(R),min(wc(x['transcript']) for x in R),max(wc(x['transcript']) for x in R),min(wc(x['note']) for x in R),max(wc(x['note']) for x in R))
